# Generated by Django 5.2.5 on 2025-10-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwinapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
            ],
        ),
    ]
